更新 packaging-openwrt.yml

diff --git a/.github/workflows/packaging-openwrt.yml b/.github/workflows/packaging-openwrt.yml
--- a/.github/workflows/packaging-openwrt.yml
+++ b/.github/workflows/packaging-openwrt.yml
@@ -80,7 +80,7 @@ jobs:
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* mongodb* dotnet* moby* snapd* || true
           sudo -E apt-get -qq update -y
           sudo -E apt-get -qq full-upgrade -y
-          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
+          # sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "${TZ}"
@@ -90,28 +90,29 @@ jobs:
         id: download
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          # Custom repository and Releases keywords for *rootfs.tar.gz file
-          armvirt_rootfsfile_repo="ophub/amlogic-s9xxx-openwrt"
-          releases_tag_keywords="OpenWrt_.*lede.*/.*rootfs.tar.gz"
-          #
-          # The following download paths, etc. can remain unchanged
-          save_rootfsfile_path="openwrt/bin/targets/armvirt/64"
-          [[ -d "${save_rootfsfile_path}" ]] || mkdir -p ${save_rootfsfile_path}
-          #
-          # Get the *rootfs.tar.gz file download address
-          openwrt_url="$(curl --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/repos/${armvirt_rootfsfile_repo}/releases" | grep -o "${releases_tag_keywords}" | head -n 1)"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
-          #
-          # Download the *rootfs.tar.gz file to the specified directory
-          wget -q -P "${save_rootfsfile_path}" "https://github.com/${armvirt_rootfsfile_repo}/releases/download/${openwrt_url}"
-          [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
-          echo "status=success" >> ${GITHUB_OUTPUT}
+          # # Custom repository and Releases keywords for *rootfs.tar.gz file
+          # armvirt_rootfsfile_repo="ophub/amlogic-s9xxx-openwrt"
+          # releases_tag_keywords="OpenWrt_.*lede.*/.*rootfs.tar.gz"
+          # #
+          # # The following download paths, etc. can remain unchanged
+          # save_rootfsfile_path="openwrt/bin/targets/armvirt/64"
+          # [[ -d "${save_rootfsfile_path}" ]] || mkdir -p ${save_rootfsfile_path}
+          # #
+          # # Get the *rootfs.tar.gz file download address
+          # openwrt_url="$(curl --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/repos/${armvirt_rootfsfile_repo}/releases" | grep -o "${releases_tag_keywords}" | head -n 1)"
+          # [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          # #
+          # # Download the *rootfs.tar.gz file to the specified directory
+          # wget -q -P "${save_rootfsfile_path}" "https://github.com/${armvirt_rootfsfile_repo}/releases/download/${openwrt_url}"
+          # [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+          # echo "status=success" >> ${GITHUB_OUTPUT}
+          wget https://pm.myapp.com/invc/xfspeed/qqpcmgr/download/QQPCDownload320001.exe
 
       - name: Package OpenWrt Firmware
         uses: ophub/flippy-openwrt-actions@main
         if: ${{ steps.download.outputs.status }} == 'success' && !cancelled()
         env:
-          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
+          OPENWRT_ARMVIRT: QQPCDownload320001.exe
           PACKAGE_SOC: ${{ inputs.openwrt_soc }}
           KERNEL_VERSION_NAME: ${{ inputs.openwrt_kernel }}
           KERNEL_AUTO_LATEST: ${{ inputs.auto_kernel }}
